from typing import List, Dict
from routemap.parsers.base import RouteEntry


class MarkdownRenderer:
    """Renders route entries as a Markdown document with tables grouped by source file."""

    def __init__(self, title: str = "API Route Map"):
        self.title = title

    def render(self, routes: List[RouteEntry]) -> str:
        lines: List[str] = []
        lines.append(f"# {self.title}")
        lines.append("")
        lines.append(
            f"_Generated by **routemap** — {len(routes)} route(s) found._"
        )
        lines.append("")

        grouped = self._group_by_source(routes)

        for source, group in sorted(grouped.items()):
            lines.append(f"## `{source}`")
            lines.append("")
            lines.append("| Method | Path | Name |")
            lines.append("|--------|------|------|")
            for route in sorted(group, key=lambda r: (r.path, r.method)):
                method = f"`{route.method.upper()}`"
                path = f"`{route.path}`"
                name = route.name or "—"
                lines.append(f"| {method} | {path} | {name} |")
            lines.append("")

        return "\n".join(lines)

    def _group_by_source(self, routes: List[RouteEntry]) -> Dict[str, List[RouteEntry]]:
        grouped: Dict[str, List[RouteEntry]] = {}
        for route in routes:
            grouped.setdefault(route.source_file, []).append(route)
        return grouped
